version: '3.1'
services:
  web:
    image: quay.io/firefoxegy/dev
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    container_name: web_container
    environment:
      - XDEBUG_REMOTE_IP=192.168.100.10
      - COMPOSER_ALLOW_SUPERUSER=1
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root